### ISSUE TITLE
BLEFloatCharacteristic instead of BLEShortCharacteristic for temperature?

### ISSUE THREAD

**Issue by mrdc** [kriswiner/nRF52832DevBoard#6]
Hello,

Using BLEShortCharacteristic for temperature decreases accuracy of displayed temp on client side - BLEFloatCharacteristic gives better precision.

https://github.com/kriswiner/nRF52832DevBoard/blob/f1ea5ac009318e7485e89b030f95ff745e53c9a5/BMP280_nRF52.ino#L122

**Comment by kriswiner** [comment]
OK, but costs and extra two bytes too...

**Comment by mrdc** [comment]
Does transmitting 2 extra bytes affect anything? 

BTW After some tests with BLEFloatCharacteristic I have problems with mobile apps which suppose to read temp: for example nRF Toolkit shows some huge values instead of a real value. Probably it can be related to conversion of transmitted data which is float32 (send as 4 bytes). The same behaviour for swift mobile app - temp is just not readable.
